ewm.date-time.pattern=yyyy-MM-dd HH:mm:ss
server.port=8080
spring.sql.init.mode=always
stats-server.url = http://localhost:9090

#Logging
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=TRACE
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
logging.level.ru.practicum.ewm.server=INFO
logging.file.name=EwmServiceApp.log

#Connection to Postgres DB
spring.datasource.driverClassName = org.postgresql.Driver
spring.datasource.url = jdbc:postgresql://localhost:5432/ewmdb
spring.datasource.username = dbuser
spring.datasource.password = 12345

#Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.format_sql=true


